version: '3.8'

services:
  app:
    container_name: my-gossip-search
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    env_file:
      - .env
    volumes:
      - data:/app/backend/data

volumes:
  data:
